name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 nose coverage flask-talisman flask-cors

    - name: Lint with flake8
      run: |
        flake8 --max-line-length=88

    - name: Test with nosetests
      run: |
        nosetests --with-coverage --cover-package=app
